spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: XXXX.apps.googleusercontent.com
            clientSecret: XXXXX
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled=true: